// Account slice end to end in headless Chrome: sign-in gates, account hub, login & security (name, password, email,
// other sessions signed out), address book with default + Deliver to, wallet, lists (create, add, move, cart, undo,
// rename, delete), browsing history (remove, clear, off switch) and 390px layout.
// Run with the app up: node e2e/account.mjs [baseUrl]   (default http://localhost:3000)
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { chromium } from 'playwright-core'

const base = process.argv[2] ?? 'http://localhost:3000'
const { products } = JSON.parse(readFileSync(new URL('../data/products.json', import.meta.url), 'utf8'))
const [p1, p2, p3] = [1, 2, 3].map((id) => products.find((p) => p.id === id))
const stamp = Date.now()
let email = `account-${stamp}@example.com`
const newEmail = `account-new-${stamp}@example.com`
const expYear = String(new Date().getFullYear() + 2)

const browser = await chromium.launch({ channel: 'chrome', headless: true })
const context = await browser.newContext({ viewport: { width: 1280, height: 900 } })
const page = await context.newPage()
const step = (name) => console.log(`- ${name}`)
const dialog = (name) => page.getByRole('dialog', { name })
const waitCart = (n) =>
  page.waitForFunction((n) => document.querySelector('a[aria-label^="Cart, "]')?.getAttribute('aria-label') === `Cart, ${n} ${n === 1 ? 'item' : 'items'}`, n)

async function signIn(p, address, password) {
  await p.getByLabel('Email').fill(address)
  await p.getByRole('button', { name: 'Continue' }).click()
  await p.getByLabel('Password', { exact: true }).fill(password)
  await p.getByRole('button', { name: 'Sign in' }).click()
}

async function addAddress(fullName, city, state, zip) {
  await page.goto(`${base}/account/addresses`)
  await page.getByRole('link', { name: 'Add address' }).click()
  await page.getByRole('heading', { name: 'Add a new address' }).waitFor()
  await page.getByLabel('Full name (First and Last name)').fill(fullName)
  await page.getByLabel('Phone number').fill('206-555-0123')
  await page.getByLabel('Address', { exact: true }).fill('123 Pine St')
  await page.getByLabel('City').fill(city)
  await page.getByLabel('Country/Region').selectOption('US') // new addresses start in the visitor's country
  await page.getByLabel('State').selectOption(state)
  await page.getByLabel('ZIP Code').fill(zip)
  await page.getByRole('button', { name: 'Add address' }).click()
  await page.getByRole('status').filter({ hasText: 'Address saved' }).waitFor()
}

try {
  step('signed out: account pages ask to sign in and come back')
  for (const path of ['/account', '/account/security', '/account/addresses', '/account/payments', '/lists', '/lists?create=1', '/history']) {
    await page.goto(base + path)
    await page.waitForURL(/\/ap\/signin\?/)
    assert.equal(new URL(page.url()).searchParams.get('return_to'), path)
  }

  step('create an account from the gate, land on Your Account')
  await page.goto(`${base}/ap/signin?return_to=%2Faccount`)
  await page.getByLabel('Email').fill(email)
  await page.getByRole('button', { name: 'Continue' }).click()
  assert.equal(await page.getByLabel('Your name').inputValue(), '', '"Your name" starts empty, not with the email')
  await page.getByLabel('Your name').fill('Ann Account')
  await page.getByLabel('Password', { exact: true }).fill('secret123')
  await page.getByLabel('Re-enter password').fill('secret123')
  await page.getByRole('button', { name: 'Create your nile account' }).click()
  await page.getByRole('heading', { level: 1, name: 'Your Account' }).waitFor()
  await page.getByText(`(${email})`).waitFor()
  await page.getByRole('link', { name: /^Your Addresses Add a delivery address/ }).waitFor()

  step('a second device signs in too')
  const other = await browser.newContext()
  const otherPage = await other.newPage()
  await otherPage.goto(`${base}/ap/signin?return_to=%2Faccount`)
  await signIn(otherPage, email, 'secret123')
  await otherPage.getByRole('heading', { level: 1, name: 'Your Account' }).waitFor()

  step('login & security: edit name, header greeting follows')
  await page.getByRole('link', { name: /^Login & security/ }).click()
  await page.getByRole('heading', { level: 1, name: 'Login & security' }).waitFor()
  await page.getByRole('button', { name: 'Edit name' }).click()
  await page.getByLabel('New name').fill('')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Enter your name.').waitFor()
  await page.getByLabel('New name').fill('Annie Renamed')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Your name has been updated.').waitFor()
  await page.getByText('Hello, Annie').waitFor()

  step('password: wrong current password rejected, then changed; the other device is signed out')
  await page.getByRole('button', { name: 'Edit password' }).click()
  await page.getByLabel('Current password').fill('wrong-password')
  await page.getByLabel('New password', { exact: true }).fill('newsecret1')
  await page.getByLabel('Reenter new password').fill('newsecret1')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Your password is incorrect.').waitFor()
  await page.getByLabel('Current password').fill('secret123')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Your password has been changed.').waitFor()
  await otherPage.goto(`${base}/account`)
  await otherPage.waitForURL(/\/ap\/signin\?/)
  await other.close()

  step('email: needs the current password, then changes')
  await page.getByRole('button', { name: 'Edit email' }).click()
  await page.getByLabel('New email address').fill(newEmail)
  await page.getByLabel('Current password').fill('secret123')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Your password is incorrect.').waitFor()
  await page.getByLabel('Current password').fill('newsecret1')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await page.getByText('Your email address has been updated.').waitFor()
  await page.getByText(newEmail).waitFor()
  email = newEmail

  step('sign out, old password fails, new password signs in; a return_to with a newline or tab stays on site')
  await page.goto(`${base}/account`)
  await page.getByRole('button', { name: 'Sign Out' }).click()
  await page.waitForURL(`${base}/`)
  await page.goto(`${base}/ap/signin?return_to=%2F%0A%2Fevil.com`)
  assert.equal(await page.locator('input[name="return_to"]').inputValue(), '/')
  await signIn(page, email, 'secret123')
  await page.getByText('Your password is incorrect.').waitFor()
  await page.getByLabel('Password', { exact: true }).fill('newsecret1')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.waitForURL(`${base}/`)
  for (const rt of ['%2F%09%2Fevil.com', '%2F%09%09%2Fevil.com', '%2F%0D%2Fevil.com', '%2F%5Cevil.com', '%2F%2Fevil.com']) {
    const res = await page.request.get(`${base}/ap/signin?return_to=${rt}`, { maxRedirects: 0 })
    assert.equal(res.headers().location, '/', `signed-in return_to=${rt} redirects home`)
  }
  await page.goto(`${base}/account`)
  await page.getByRole('heading', { level: 1, name: 'Your Account' }).waitFor()

  step('addresses: validation, add two, set the second as default, Deliver to follows')
  await page.goto(`${base}/account/addresses/new`)
  const nameField = page.getByLabel('Full name (First and Last name)')
  assert.notEqual(await nameField.inputValue(), '', 'a new address starts with the account name')
  await nameField.fill('')
  await page.getByRole('button', { name: 'Add address' }).click()
  await page.getByText('Please enter a name.').waitFor()
  await addAddress('Ann Seattle', 'Seattle', 'WA', '98101')
  await page.getByRole('link', { name: /^Deliver to Ann/ }).waitFor()
  await addAddress('Ben Newyork', 'New York', 'NY', '10001')
  await page.getByRole('article', { name: 'Default address: Ann Seattle' }).waitFor()
  await page.getByRole('button', { name: 'Set address for Ben Newyork as default' }).click()
  await page.getByRole('status').filter({ hasText: 'Default address changed' }).waitFor()
  await page.getByRole('article', { name: 'Default address: Ben Newyork' }).waitFor()
  await page.getByRole('link', { name: /^Deliver to Ben/ }).waitFor()

  step('addresses: remove asks first; missing ids are 404')
  await page.getByRole('button', { name: 'Remove address for Ann Seattle' }).click()
  await dialog('Confirm removal').getByRole('button', { name: 'No' }).click()
  await dialog('Confirm removal').waitFor({ state: 'hidden' })
  await page.getByRole('button', { name: 'Remove address for Ann Seattle' }).click()
  await dialog('Confirm removal').getByRole('button', { name: 'Yes' }).click()
  await page.getByRole('status').filter({ hasText: 'Address removed' }).waitFor()
  assert.equal(await page.getByRole('article', { name: /Ann Seattle/ }).count(), 0)
  assert.equal((await page.goto(`${base}/account/addresses/00000000-0000-0000-0000-000000000000/edit`)).status(), 404)
  assert.equal((await page.goto(`${base}/lists/not-a-list`)).status(), 404)

  step('payments: empty wallet, add a card, remove it')
  await page.goto(`${base}/account/payments`)
  await page.getByText("You don't have any payment methods saved.").waitFor()
  await page.getByRole('link', { name: 'Add a payment method' }).click()
  await page.getByLabel('Card number').fill('4242 4242 4242 4242')
  await page.getByLabel('Name on card').fill('Annie Renamed')
  await page.getByLabel('Expiration month').selectOption('12')
  await page.getByLabel('Expiration year').selectOption(expYear)
  await page.getByLabel('Security code (CVV)').fill('123')
  await page.getByRole('button', { name: 'Add your card' }).click()
  await page.getByRole('status').filter({ hasText: 'Card added' }).waitFor()
  await page.getByRole('listitem', { name: 'Visa ending in 4242' }).getByText('Default').waitFor()
  await page.getByRole('button', { name: 'Remove Visa ending in 4242' }).click()
  await dialog('Remove card').getByRole('button', { name: 'Confirm Remove' }).click()
  await page.getByRole('status').filter({ hasText: 'Card removed' }).waitFor()
  await page.getByText("You don't have any payment methods saved.").waitFor()

  step('lists: create via ?create=1 with validation and duplicate names')
  await page.goto(`${base}/lists?create=1`)
  await dialog('Create a new list').getByRole('button', { name: 'Create List' }).click()
  await page.getByText('Please enter a list name').waitFor()
  await page.getByLabel('List name').fill('Birthday')
  await page.getByRole('button', { name: 'Create List' }).click()
  await page.waitForURL(/\/lists\/[0-9a-f-]{36}$/)
  const birthdayUrl = page.url()
  await page.getByRole('heading', { level: 2, name: 'Birthday' }).waitFor()
  await page.getByText('This list is empty').waitFor()
  await page.getByRole('link', { name: 'Create a List' }).click()
  await page.getByLabel('List name').fill('birthday')
  await page.getByRole('button', { name: 'Create List' }).click()
  await page.getByText('You already have a list with this name.').waitFor()
  await page.keyboard.press('Escape')
  await page.waitForURL(birthdayUrl)

  step('lists: Add to List on a product page, then move it to the new list')
  await page.goto(`${base}/dp/${p1.id}`)
  await page.getByRole('button', { name: 'Add to List', exact: true }).click()
  await page.getByText('Added to Shopping List').waitFor()
  await page.goto(`${base}/lists`)
  await page.getByRole('heading', { level: 2, name: 'Shopping List' }).waitFor()
  await page.getByText('Item added ').waitFor()
  await page.getByRole('button', { name: `Move ${p1.title}` }).click()
  await page.getByRole('group', { name: 'Move to' }).getByRole('button', { name: 'Birthday' }).click()
  await page.getByText('Moved to Birthday').waitFor()
  await page.getByRole('link', { name: 'View list' }).click()
  await page.waitForURL(birthdayUrl)
  await page.getByRole('link', { name: p1.title }).waitFor()

  step('lists: add to cart from the list (item stays), delete with undo')
  await page.getByRole('button', { name: 'Add to cart' }).click()
  await waitCart(1)
  await page.getByRole('button', { name: `Delete ${p1.title}` }).click()
  await page.getByText('Deleted').waitFor()
  await page.getByRole('button', { name: 'Undo' }).click()
  await page.getByRole('link', { name: p1.title }).waitFor()

  step('lists: rename, then delete the list')
  await page.getByRole('button', { name: 'Rename list' }).click()
  await page.getByLabel('List name').fill('Birthday 2026')
  await page.getByRole('button', { name: 'Save' }).click()
  await page.getByRole('heading', { level: 2, name: 'Birthday 2026' }).waitFor()
  await page.getByRole('button', { name: 'Delete list' }).click()
  await dialog('Delete list').getByText('This removes the 1 item on it.').waitFor()
  await dialog('Delete list').getByRole('button', { name: 'Delete' }).click()
  await page.waitForURL(`${base}/lists`)
  await page.getByRole('heading', { level: 2, name: 'Shopping List' }).waitFor()
  assert.equal(await page.getByRole('navigation', { name: 'Your lists' }).getByText('Birthday 2026').count(), 0)

  step('history: two viewed products, newest first; remove one; clear all; switch off')
  await page.goto(`${base}/dp/${p2.id}`)
  await page.goto(`${base}/dp/${p3.id}`)
  await page.goto(`${base}/history`)
  for (let i = 0; i < 5 && !(await page.getByRole('link', { name: p3.title }).first().isVisible()); i++) await page.reload() // views record after the response
  await page.getByRole('heading', { level: 2, name: p2.title }).waitFor()
  const titles = await page.getByRole('main').locator('li h2').allTextContents()
  assert.deepEqual(titles.slice(0, 2), [p3.title, p2.title])
  await page.getByRole('button', { name: `Remove ${p2.title} from view` }).click()
  await page.getByRole('heading', { level: 2, name: p2.title }).waitFor({ state: 'detached' })
  await page.getByRole('heading', { level: 2, name: p3.title }).waitFor()
  await page.getByRole('button', { name: 'Remove all items' }).click()
  await dialog('Remove all items').getByRole('button', { name: 'Remove all' }).click()
  await page.getByText('You have no recently viewed items.').waitFor()
  const toggle = page.getByRole('switch', { name: 'Browsing history' })
  assert.equal(await toggle.getAttribute('aria-checked'), 'true')
  await toggle.click()
  await page.getByText("Browsing history is turned off. Items you view won't appear here.").waitFor()
  await page.goto(`${base}/dp/${p2.id}`)
  await page.goto(`${base}/history`)
  await page.getByRole('switch', { name: 'Browsing history' }).click()
  await page.getByText('You have no recently viewed items.').waitFor()

  step('hub reflects it all')
  await page.goto(`${base}/account`)
  await page.getByRole('link', { name: /^Your Addresses Default: 123 Pine St, New York/ }).waitFor()
  await page.getByRole('link', { name: /^Your Payments Add a credit or debit card/ }).waitFor()
  await page.getByRole('link', { name: /^Your Lists 1 list · 0 items/ }).waitFor()

  step('390px wide: no horizontal page scroll')
  await page.setViewportSize({ width: 390, height: 844 })
  for (const path of ['/account', '/account/security', '/account/addresses', '/account/addresses/new', '/account/payments?add=1', '/lists', '/history']) {
    await page.goto(base + path)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
    assert.ok(overflow <= 0, `${path} overflows by ${overflow}px`)
  }

  console.log('account e2e ok')
} catch (e) {
  await page.screenshot({ path: 'e2e/account-failure.png', fullPage: true }).catch(() => {})
  console.error(`failed at ${page.url()} (screenshot: e2e/account-failure.png)`)
  throw e
} finally {
  await browser.close()
}
