// Home page, Today's Deals and Best Sellers through headless Chrome.
// Run with the app up: node e2e/home.mjs [baseUrl]   (default http://localhost:3000)
import assert from 'node:assert/strict'
import { chromium } from 'playwright-core'

const base = process.argv[2] ?? 'http://localhost:3000'
const browser = await chromium.launch({ channel: 'chrome', headless: true })
const page = await browser.newPage({ viewport: { width: 1536, height: 820 } })
const step = (name) => console.log(`- ${name}`)
const region = (name) => page.getByRole('region', { name, exact: true })
const cartCount = async () => Number((await page.getByRole('link', { name: /^Cart, / }).getAttribute('aria-label')).match(/\d+/)[0])
const cards = () => page.locator('main li article')
const homeCards = () => page.locator('main h2.font-display')
const decode = (html) => html.replaceAll('&amp;', '&').replaceAll('&#x27;', "'").replaceAll('&quot;', '"')

try {
  step('signed-out home: picture tiles scroll both ways and load eagerly, nothing overlaps the cards')
  await page.goto(base)
  const tiles = page.getByRole('list', { name: 'Shop by department' })
  const scrollLeft = () => tiles.evaluate((el) => el.scrollLeft)
  assert.ok((await tiles.getByRole('link').count()) >= 6, 'tiles')
  assert.equal(await tiles.locator('img[loading="lazy"]').count(), 0, 'tile images are eager')
  const left = page.getByRole('button', { name: 'Scroll departments left' })
  const right = page.getByRole('button', { name: 'Scroll departments right' })
  assert.equal(await left.isVisible(), false, 'no left arrow at the start')
  await right.click()
  await left.waitFor()
  await page.waitForFunction(() => document.querySelector('[aria-label="Shop by department"]').scrollLeft > 200)
  await left.click()
  await left.waitFor({ state: 'hidden' })
  assert.equal(await scrollLeft(), 0)
  assert.equal(await page.locator('[aria-roledescription="carousel"]').count(), 0, 'no hero banner')
  const tilesBox = await tiles.boundingBox()
  const firstCard = await homeCards().first().locator('..').boundingBox()
  assert.ok(firstCard.y >= tilesBox.y + tilesBox.height, 'cards start below the tiles')

  step('bordered 2x2 cards in four columns, carousels between them, sign-in block at the bottom')
  assert.equal(await homeCards().count(), 24)
  for (const name of ['Plug in with our electronics', 'Popular finds under $25', 'Deals on top categories', 'Explore Best Sellers']) await page.getByRole('heading', { name }).waitFor()
  const firstRow = await homeCards().evaluateAll((hs) => hs.slice(0, 5).map((h) => Math.round(h.parentElement.getBoundingClientRect().top)))
  assert.equal(new Set(firstRow.slice(0, 4)).size, 1, 'four cards share the first row')
  assert.ok(firstRow[4] > firstRow[0], 'the fifth card wraps')
  for (const name of ["Today's Deals", 'Best Sellers in Home & Kitchen']) {
    assert.ok((await region(name).locator('li').count()) >= 5, `${name} carousel has items`)
  }
  // nothing expires, so the tag says "Deal" (product-map §4.2)
  assert.ok((await region("Today's Deals").getByText('Deal', { exact: true }).count()) >= 5)
  assert.equal(await page.getByText(/limited time deal/i).count(), 0)
  assert.equal(await page.locator('header a[href="/s?i=automotive"]').count(), 0, 'no Automotive department')
  await page.getByText('See personalized recommendations').waitFor()
  assert.equal(await page.getByRole('heading', { name: 'Pick up where you left off' }).count(), 0)

  step('every tile and card link opens a page with results, and each card picture is on its destination')
  const links = await page.evaluate(() => {
    const tileLinks = [...document.querySelectorAll('[aria-label="Shop by department"] a')].map((a) => ({ href: a.getAttribute('href') }))
    const cardLinks = [...document.querySelectorAll('main h2.font-display')].flatMap((h) => [
      { href: h.querySelector('a').getAttribute('href') },
      ...[...h.parentElement.querySelectorAll('ul a')].map((a) => ({ href: a.getAttribute('href'), image: a.querySelector('img').getAttribute('src'), label: a.textContent })),
    ])
    return [...tileLinks, ...cardLinks]
  })
  assert.ok(links.length >= 24 * 5, 'links collected')
  const bodies = new Map()
  const unique = [...new Set(links.map((l) => l.href))]
  for (let i = 0; i < unique.length; i += 6) {
    await Promise.all(
      unique.slice(i, i + 6).map(async (href) => {
        const res = await page.request.get(base + href)
        assert.equal(res.status(), 200, href)
        bodies.set(href, decode(await res.text()))
      }),
    )
  }
  for (const [href, body] of bodies) {
    assert.ok(!body.includes('No results for') && !body.includes('No deals match'), `${href} is empty`)
  }
  for (const { href, image, label } of links.filter((l) => l.image)) assert.ok(bodies.get(href).includes(image), `"${label}" picture ${image} is not on ${href}`)

  step('keyboard: skip link comes first; the All drawer hands focus back when it closes')
  await page.goto(base)
  await page.keyboard.press('Tab')
  assert.equal(await page.evaluate(() => document.activeElement.textContent), 'Skip to main content')
  const allButton = page.getByRole('button', { name: 'Open menu: all departments' }).filter({ visible: true })
  await allButton.click()
  await page.getByRole('dialog', { name: 'All departments' }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('dialog', { name: 'All departments' }).waitFor({ state: 'detached' })
  assert.ok(await allButton.evaluate((el) => el === document.activeElement), 'focus returns to the All button')

  step('guest sets a delivery ZIP in place')
  await page.getByRole('button', { name: /^Deliver(?:ing)? to / }).click()
  const location = page.getByRole('dialog', { name: 'Choose your location' })
  await location.getByLabel('US zip code').fill('98l09')
  await location.getByRole('button', { name: 'Apply' }).click()
  await location.getByText('Please enter a valid US zip code').waitFor()
  await location.getByLabel('US zip code').fill('98109')
  await location.getByRole('button', { name: 'Apply' }).click()
  await page.getByRole('button', { name: /^Delivering to 98109/ }).waitFor()
  assert.equal(page.url(), `${base}/`)

  step('deals: department chip, discount facet and sort narrow and order the grid')
  await page.goto(`${base}/deals`)
  await page.getByRole('heading', { name: "Today's Deals", level: 1 }).waitFor()
  const total = await cards().count()
  assert.ok(total > 20)
  await page.getByRole('navigation', { name: 'Deal departments' }).getByRole('link', { name: 'Electronics', exact: true }).click()
  await page.waitForURL(/[?&]i=electronics/)
  await page.getByRole('heading', { name: /deals in Electronics/ }).waitFor()
  const inElectronics = await cards().count()
  assert.ok(inElectronics > 0 && inElectronics < total)
  await page.getByRole('link', { name: '15% off or more' }).click()
  await page.waitForURL(/discount=15/)
  const discounted = await cards().count()
  assert.ok(discounted > 0 && discounted <= inElectronics)
  await page.getByLabel('Sort by:').selectOption('price-asc')
  await page.waitForURL(/sort=price-asc/)
  assert.ok(page.url().includes('i=electronics') && page.url().includes('discount=15'), 'sort keeps the filters')
  const prices = (await cards().evaluateAll((els) => els.map((el) => Number(el.dataset.price))))
  assert.deepEqual(prices, [...prices].sort((a, b) => a - b))
  for (const badge of await cards().locator('.bg-deal').allTextContents()) assert.ok(Number(badge.match(/\d+/)[0]) >= 15, badge)

  step('deals: empty state for a filter with no deals, then clear')
  await page.goto(`${base}/deals?discount=50`)
  await page.getByText('No deals match your filters').waitFor()
  await page.getByRole('link', { name: 'Clear all filters' }).click()
  await page.waitForURL(`${base}/deals`)

  step('deals: add a deal to the cart, header count increments')
  const before = await cartCount()
  const deal = cards().first()
  await deal.getByRole('button', { name: 'Add to cart' }).click()
  await deal.getByText('in cart').waitFor()
  await page.getByRole('link', { name: new RegExp(`^Cart, ${before + 1} items?$`) }).waitFor()

  step('best sellers: department and category navigation with ranks; invalid slug is a 404')
  await page.goto(`${base}/bestsellers`)
  await page.getByRole('heading', { name: 'nile Best Sellers', level: 1 }).waitFor()
  await page.getByText('Our most popular products based on sales. Updated frequently.').waitFor()
  const rail = page.getByRole('navigation', { name: 'Best Sellers departments' })
  await rail.getByRole('link', { name: 'Electronics', exact: true }).click()
  await page.waitForURL(`${base}/bestsellers/electronics`)
  await page.getByRole('heading', { name: 'Best Sellers in Electronics', level: 1 }).waitFor()
  assert.deepEqual(await cards().locator('span.absolute').evaluateAll((els) => els.slice(0, 3).map((el) => el.textContent)), ['#1', '#2', '#3'])
  await rail.getByRole('link', { name: 'Laptops', exact: true }).click()
  await page.waitForURL(`${base}/bestsellers/laptops`)
  await page.getByRole('heading', { name: 'Best Sellers in Laptops', level: 1 }).waitFor()
  await rail.getByRole('link', { name: '‹ Electronics' }).click()
  await page.waitForURL(`${base}/bestsellers/electronics`)
  await rail.getByRole('link', { name: '‹ Any Department' }).click()
  await page.waitForURL(`${base}/bestsellers`)
  for (const slug of ['not-a-department', 'toString', 'automotive']) assert.equal((await page.goto(`${base}/bestsellers/${slug}`)).status(), 404)

  step('390px: no sideways scroll; home cards stack in one column; filter rails open from a toggle')
  await page.setViewportSize({ width: 390, height: 844 })
  for (const path of ['/', '/deals', '/bestsellers', '/bestsellers/electronics']) {
    await page.goto(base + path)
    const overflow = await page.evaluate(() => document.documentElement.scrollWidth - window.innerWidth)
    assert.ok(overflow <= 0, `${path} overflows by ${overflow}px`)
  }
  await page.goto(base)
  const stacked = await homeCards().evaluateAll((hs) => hs.slice(0, 2).map((h) => h.parentElement.getBoundingClientRect()).map((r) => [r.left, r.top]))
  assert.ok(stacked[0][0] === stacked[1][0] && stacked[1][1] > stacked[0][1], 'one column')
  await page.goto(`${base}/deals`)
  assert.equal(await page.getByRole('link', { name: '10% off or more' }).isVisible(), false)
  await page.getByRole('button', { name: 'Filters' }).click()
  await page.getByRole('link', { name: '10% off or more' }).waitFor()

  step('signed in: no sign-in block; browsing history adds "Pick up where you left off" as the first card')
  await page.setViewportSize({ width: 1536, height: 820 })
  await page.goto(`${base}/ap/signin`)
  const email = `home-${Date.now()}@example.com`
  await page.getByLabel('Email').fill(email)
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Your name').fill('Hana Home')
  await page.getByLabel('Password', { exact: true }).fill('secret123')
  await page.getByLabel('Re-enter password').fill('secret123')
  await page.getByRole('button', { name: 'Create your nile account' }).click()
  await page.getByText('Hello, Hana').waitFor()
  await page.goto(base)
  await page.getByText('After viewing product detail pages').waitFor()
  assert.equal(await page.getByText('See personalized recommendations').count(), 0)
  const viewedHref = await region('Best Sellers in Home & Kitchen').locator('a[href^="/dp/"]').first().getAttribute('href')
  await page.goto(base + viewedHref)
  await page.goto(base)
  // the view is recorded after the product page's response, so allow one reload
  const pickUp = page.getByRole('heading', { name: 'Pick up where you left off' })
  if (!(await pickUp.count())) await page.reload()
  await pickUp.locator('..').locator(`a[href="${viewedHref}"]`).first().waitFor()
  assert.equal(await homeCards().first().textContent(), 'Pick up where you left off')
  assert.equal(await homeCards().count(), 24, 'the personal card replaces a generic one')
  await region('Inspired by your browsing history').waitFor()
  await page.getByRole('link', { name: 'View or edit your browsing history' }).waitFor()

  // the header outlives the Sign Out redirect, so the menu or drawer it came from has to close itself
  step('Sign Out closes the keyboard-opened Account & Lists menu')
  await page.mouse.move(700, 800)
  const caret = page.getByRole('button', { name: 'Account & Lists menu' })
  await caret.focus()
  await page.keyboard.press('Enter')
  const accountPanel = page.locator(`[id="${await caret.getAttribute('aria-controls')}"]`)
  await accountPanel.getByRole('button', { name: 'Sign Out' }).focus()
  await page.keyboard.press('Enter')
  await page.getByRole('link', { name: /^Hello, sign in/ }).first().waitFor()
  assert.equal(await caret.getAttribute('aria-expanded'), 'false')
  assert.ok(await accountPanel.evaluate((el) => el.hidden), 'account menu closed')

  step('Sign Out from the All drawer closes the drawer')
  await page.goto(`${base}/ap/signin`)
  await page.getByLabel('Email').fill(email)
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Password', { exact: true }).fill('secret123')
  await page.getByRole('button', { name: 'Sign in' }).click()
  await page.getByText('Hello, Hana').first().waitFor()
  await page.goto(`${base}/deals`)
  await allButton.click()
  await page.getByRole('dialog', { name: 'All departments' }).getByRole('button', { name: 'Sign Out' }).click()
  await page.waitForURL(`${base}/`)
  await page.getByRole('link', { name: /^Hello, sign in/ }).first().waitFor()
  await page.waitForTimeout(500)
  assert.equal(await page.getByRole('dialog', { name: 'All departments' }).count(), 0, 'drawer closed')

  console.log('e2e home ok')
} catch (e) {
  await page.screenshot({ path: 'e2e/home-failure.png', fullPage: true }).catch(() => {})
  console.error(`failed at ${page.url()} (screenshot: e2e/home-failure.png)`)
  throw e
} finally {
  await browser.close()
}
